trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'Install dependencies and run tests'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: '<your_dockerhub_username>/azure-devops-demo'
    dockerfile: '**/Dockerfile'
    containerRegistry: 'DockerHub'
    tags: |
      $(Build.BuildId)
  displayName: 'Build and push Docker image'

