trigger:
- main

pool:
  name: 'Default'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
  displayName: 'Install JDK 8'

- script: |
    javac HelloWorld.java
    java HelloWorld
  displayName: 'Compile and run HelloWorld.java'
